---
name: CPAN-Mini-Devel
version: 0.03
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Create CPAN::Mini mirror with developer releases
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
  repository: http://dagolden.googlecode.com/svn/
requires:
  CPAN: 1.92
  CPAN::HandleConfig: 0
  CPAN::Mini: 0.567
  CPAN::Tarzip: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 3.27
  File::Temp: 0.2
  perl: 5.006
build_requires:
  Test::More: 0.62
provides:
  CPAN::Mini::Devel:
    file: lib/CPAN/Mini/Devel.pm
    version: 0.03
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
